branches:
  only:
  - master
image: Ubuntu
services:
  - docker
init:
  - docker pull devkitpro/devkita64
install:
  - ps: |
      $version = Get-Date -Format "mmddyyyy-HHmm"
      Update-AppveyorBuild -Version "0.1-$version"
  - ls -al
  - docker run --mount type=bind,source="$(pwd)",target=/home -w/home devkitpro/devkita64 make
  - mkdir media
  - touch media/oggs_go_here
  - 7z a -r SchalterVox.zip SchalterVox.nro media
  - ls -al
artifacts:
  - path: SchalterVox.zip
    name: SchalterVox
deploy:
  release: SchalterVox-v$(appveyor_build_version)
  description: 'SchalterVox Media Player - Nightly AppVeyor Build'
  provider: GitHub
  auth_token:
    secure: GZjRDISrpqmTNVinnfQ2vCSrwYUBsukPJGaBSkojxhP3OpfGmxEGhkHW8fmcDcud
  artifact: \.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: master
      
build: off
test: off
