skip_tags: true
branches:
  only:
  - master
image: Ubuntu
services:
  - docker
init:
  - docker pull devkitpro/devkita64
install:
  - ps: |
      $version = Get-Date -Format "yyyyddMM-HHmmss"
      Update-AppveyorBuild -Version "$version"
  - ls -al
  - docker run --mount type=bind,source="$(pwd)",target=/home/SchalterVox -w/home/SchalterVox devkitpro/devkita64 make
  - mkdir media
  - touch media/oggs_go_here
  - 7z a -r SchalterVox.zip SchalterVox.nro media
  - ls -al
artifacts:
  - path: SchalterVox.zip
    name: SchalterVox
deploy:
  release: SchalterVox-$(APPVEYOR_BUILD_VERSION)
  description: 'SchalterVox Media Player - AppVeyor Build'
  provider: GitHub
  auth_token:
    secure: GZjRDISrpqmTNVinnfQ2vCSrwYUBsukPJGaBSkojxhP3OpfGmxEGhkHW8fmcDcud
  artifact: SchalterVox.zip
  draft: false
  prerelease: true
  on:
    branch: master
      
build: off
test: off
